[package]
name = "cargo-cult"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
russh = "0.45.0"
russh-keys = "0.45.0"
tokio = { version = "1.41.0", features = ["full"] }
async-trait = "0.1.83"
futures = "0.3.31"
